version: "3.9"

services:
  nginx:
    build: 
      context: ./nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    volumes:
      - ${HTML_HOST_ROOT_DIRECTORY}:/var/www/html
    container_name: nginx
    networks:
      - d_li
      
  php:
    build: 
      context: ./php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ${HTML_HOST_ROOT_DIRECTORY}:/var/www/html
    container_name: php
    networks:
      - d_li
    ports:
      - "9000:9000"

  node:
    image: node:lts
    volumes:
      - ${HTML_HOST_ROOT_DIRECTORY}:/var/www/html
    command: tail -f /dev/null
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    container_name: node
    networks:
      - d_li
  
  db:
    image: mysql:9.2.0
    ports: 
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    container_name: db

  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    container_name: phpmyadmin

networks:
  d_li:

volumes:
  db_data:
